--------------------------------------------------------
-- Archivo creado  - domingo-abril-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARROSOLAR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CARROSOLAR" 
   (	"ID_CARRO" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"PLACA" VARCHAR2(10 BYTE), 
	"ESTADO" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."ID_CARRO" IS 'Número que identifica el carro dentro del proyecto';
   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."NOMBRE" IS 'Nombre del vehículo';
   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."PLACA" IS 'Placa que es dada por el Word Solar Challenge e identifica los carros durante la carrera';
   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."ESTADO" IS 'Estado del vehículo. Puede tomar los siguientes valores: activo o inactivo.';
--------------------------------------------------------
--  DDL for Index CARROSOLAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CARROSOLAR_PK" ON "SYSTEM"."CARROSOLAR" ("ID_CARRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CARROSOLAR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CARROSOLAR" ADD CONSTRAINT "CARROSOLAR_CHK_ESTADO" CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')) ENABLE;
  ALTER TABLE "SYSTEM"."CARROSOLAR" ADD CONSTRAINT "CARROSOLAR_PK" PRIMARY KEY ("ID_CARRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("PLACA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("ID_CARRO" NOT NULL ENABLE);
