--------------------------------------------------------
-- Archivo creado  - domingo-abril-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DONACION_MONETARIA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DONACION_MONETARIA" 
   (	"ID_MONETARIA" NUMBER(15,0), 
	"ID_PATROCINADOR" NUMBER(15,0), 
	"ID_CARRO" NUMBER(15,0), 
	"CANTIDAD" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."ID_MONETARIA" IS 'Número único que identifica cada donación monetaria. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."ID_PATROCINADOR" IS 'Número único que identifica un patrocinador de otro. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."ID_CARRO" IS 'Número que identifica el carro dentro del proyecto. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."CANTIDAD" IS 'Cantidad en pesos colombianos. ';
--------------------------------------------------------
--  DDL for Index DONACION_MONETARIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DONACION_MONETARIA_PK" ON "SYSTEM"."DONACION_MONETARIA" ("ID_MONETARIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DONACION_MONETARIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" ADD CONSTRAINT "DONACION_MONETARIA_PK" PRIMARY KEY ("ID_MONETARIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("ID_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("ID_PATROCINADOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("ID_MONETARIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DONACION_MONETARIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" ADD CONSTRAINT "DONACION_MONETARIA_FK1" FOREIGN KEY ("ID_PATROCINADOR")
	  REFERENCES "SYSTEM"."PATROCINADOR" ("ID_PATROCINADOR") ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" ADD CONSTRAINT "DONACION_MONETARIA_FK2" FOREIGN KEY ("ID_CARRO")
	  REFERENCES "SYSTEM"."CARROSOLAR" ("ID_CARRO") ENABLE;
