--------------------------------------------------------
-- Archivo creado  - domingo-abril-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSONAL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PERSONAL" 
   (	"IDENTIFICACION" NUMBER(15,0), 
	"ID_SUBSISTEMA" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"TELEFONO" VARCHAR2(15 BYTE), 
	"CORREO" VARCHAR2(30 BYTE), 
	"TIPO" VARCHAR2(15 BYTE), 
	"ESTADO" VARCHAR2(15 BYTE), 
	"PAGO" NUMBER(8,0), 
	"PROFESION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."IDENTIFICACION" IS 'Número de identificación único de la persona.  ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."ID_SUBSISTEMA" IS 'Número que identifica un subsitema de otro dentro del proyecto. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."NOMBRE" IS 'Nombre completo de la persona. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."TELEFONO" IS 'Número de teléfono celular de la persona. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."CORREO" IS 'Correo electrónico de la persona. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."TIPO" IS 'Tipo. Puede tomar los siguientes valores: estudiante interno, estudiante externo, profesor, persona externa. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."ESTADO" IS 'Estado de la persona. Puede tomar los siguientes valores: activa o inactiva ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."PAGO" IS 'Pago. Cantidad en pesos colombianos ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."PROFESION" IS 'Pregrado del estudiante o profesión de la cual se graduó. ';
--------------------------------------------------------
--  DDL for Index PERSONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PERSONAL_PK" ON "SYSTEM"."PERSONAL" ("IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PERSONAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_CHK_ESTADO" CHECK (ESTADO IN ('ACTIVO','INACTIVO')) ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_PK" PRIMARY KEY ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("PROFESION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("PAGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("ID_SUBSISTEMA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PERSONAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERTENECE_FK" FOREIGN KEY ("ID_SUBSISTEMA")
	  REFERENCES "SYSTEM"."SUBSISTEMA" ("ID_SUBSISTEMA") ENABLE;
