--------------------------------------------------------
-- Archivo creado  - domingo-abril-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBSISTEMA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUBSISTEMA" 
   (	"ID_SUBSISTEMA" NUMBER(15,0), 
	"ID_CARRO" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"ESTADO" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."ID_SUBSISTEMA" IS 'Número que identifica un subsitema de otro dentro del proyecto';
   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."ID_CARRO" IS 'Número que identifica el carro dentro del proyecto.';
   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."NOMBRE" IS 'Nombre del subsitema ';
   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."ESTADO" IS 'Estado del subsitema. Puede tomar los siguientes valores: activo o inactivo. ';
--------------------------------------------------------
--  DDL for Index SUBSISTEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SUBSISTEMA_PK" ON "SYSTEM"."SUBSISTEMA" ("ID_SUBSISTEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUBSISTEMA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSISTEMA" ADD CONSTRAINT "SUBSISTEMA_CHK_ESTADO" CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')) ENABLE;
  ALTER TABLE "SYSTEM"."SUBSISTEMA" ADD CONSTRAINT "SUBSISTEMA_PK" PRIMARY KEY ("ID_SUBSISTEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("ID_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("ID_SUBSISTEMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SUBSISTEMA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSISTEMA" ADD CONSTRAINT "SUBSISTEMA_FK1" FOREIGN KEY ("ID_CARRO")
	  REFERENCES "SYSTEM"."CARROSOLAR" ("ID_CARRO") ENABLE;
