--------------------------------------------------------
-- Archivo creado  - domingo-mayo-22-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARROSOLAR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CARROSOLAR" 
   (	"ID_CARRO" NUMBER(15,0), 
	"NOMBRE_CARRO" VARCHAR2(20 BYTE), 
	"PLACA_CARRO" VARCHAR2(6 BYTE), 
	"ESTADO_CARRO" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."ID_CARRO" IS 'N�mero que identifica el carro dentro del proyecto';
   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."NOMBRE_CARRO" IS 'Nombre del veh�culo';
   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."PLACA_CARRO" IS 'Placa que es dada por el Word Solar Challenge e identifica los carros durante la carrera';
   COMMENT ON COLUMN "SYSTEM"."CARROSOLAR"."ESTADO_CARRO" IS 'Estado del veh�culo. Puede tomar los siguientes valores: activo o inactivo.';
--------------------------------------------------------
--  DDL for Table DONACION_MATERIAL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DONACION_MATERIAL" 
   (	"ID_DONMATERIAL" NUMBER(15,0), 
	"ID_PATROCINADOR" NUMBER(15,0), 
	"ID_SUBSISTEMA" NUMBER(15,0), 
	"CANTIDAD_MAT" NUMBER(6,0), 
	"FECHA_DONMAT" DATE, 
	"ID_MATERIAL" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."DONACION_MATERIAL"."ID_DONMATERIAL" IS 'N�mero �nico que identifica cada donaci�n de material. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MATERIAL"."ID_PATROCINADOR" IS 'N�mero �nico que identifica un patrocinador de otro. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MATERIAL"."ID_SUBSISTEMA" IS 'N�mero que identifica un subsitema de otro dentro del proyecto. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MATERIAL"."CANTIDAD_MAT" IS 'N�mero de piezas donadas. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MATERIAL"."FECHA_DONMAT" IS 'Fecha en la que se realiza la donacion del material';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MATERIAL"."ID_MATERIAL" IS 'Numero que identifica el material donado';
--------------------------------------------------------
--  DDL for Table DONACION_MONETARIA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DONACION_MONETARIA" 
   (	"ID_MONETARIA" NUMBER(15,0), 
	"ID_PATROCINADOR" NUMBER(15,0), 
	"ID_CARRO" NUMBER(15,0), 
	"CANTIDAD_MONE_ORIGINAL" NUMBER(30,0), 
	"FECHA_MONE" DATE, 
	"ID_TIPOMONEDA" VARCHAR2(3 BYTE), 
	"TASA_CAMBIO" NUMBER(30,0), 
	"CANTIDAD_COP" NUMBER(30,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."ID_MONETARIA" IS 'N�mero �nico que identifica cada donaci�n monetaria. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."ID_PATROCINADOR" IS 'N�mero �nico que identifica un patrocinador de otro. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."ID_CARRO" IS 'N�mero que identifica el carro dentro del proyecto. ';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."CANTIDAD_MONE_ORIGINAL" IS 'Cantidad de dinero en moneda original';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."FECHA_MONE" IS 'Fecha en la que se realiza la donacion monetaria';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."ID_TIPOMONEDA" IS 'Numero que identifica el tipo de moneda en el que se realiza la donacion';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."TASA_CAMBIO" IS 'Valor en el que se encuentra el peso colombiano respecto a la moneda en la que se realiza la donacion';
   COMMENT ON COLUMN "SYSTEM"."DONACION_MONETARIA"."CANTIDAD_COP" IS 'Cantidad de la donacion monetaria en pesos colombianos';
--------------------------------------------------------
--  DDL for Table EPS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EPS" 
   (	"ID_EPS" NUMBER(15,0), 
	"NOMBRE_EPS" VARCHAR2(50 BYTE), 
	"TELEFONO_EPS" VARCHAR2(20 BYTE), 
	"CIUDAD_EPS" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."EPS"."ID_EPS" IS 'Numero que identifica la eps';
   COMMENT ON COLUMN "SYSTEM"."EPS"."NOMBRE_EPS" IS 'Nombre de la eps';
   COMMENT ON COLUMN "SYSTEM"."EPS"."TELEFONO_EPS" IS 'Telefono de la sede principal de la EPS';
   COMMENT ON COLUMN "SYSTEM"."EPS"."CIUDAD_EPS" IS 'Ciudad de la sede principal de la EPS';
--------------------------------------------------------
--  DDL for Table GASTOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GASTOS" 
   (	"ID_GASTO" NUMBER(5,0), 
	"ID_CARRO" NUMBER(15,0), 
	"CANTIDAD_GASTO" NUMBER(10,0), 
	"DESC_GASTO" VARCHAR2(50 BYTE), 
	"FECHA_GASTO" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."GASTOS"."ID_GASTO" IS 'Numero unico que identifica cada gasto que realiza un carr';
   COMMENT ON COLUMN "SYSTEM"."GASTOS"."ID_CARRO" IS 'Numero unico que identifica el carro que realiza el carro';
   COMMENT ON COLUMN "SYSTEM"."GASTOS"."CANTIDAD_GASTO" IS 'Cantidad en pesos colombianos del gasto realizado';
   COMMENT ON COLUMN "SYSTEM"."GASTOS"."DESC_GASTO" IS 'Descripcion breve del gasto';
   COMMENT ON COLUMN "SYSTEM"."GASTOS"."FECHA_GASTO" IS 'Fecha en la que se realiza el gasto';
--------------------------------------------------------
--  DDL for Table LABORATORIOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LABORATORIOS" 
   (	"ID_LABORATORIO" NUMBER(15,0), 
	"NOMBRE_LAB" VARCHAR2(30 BYTE), 
	"TAMA�O_LAB" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."LABORATORIOS"."ID_LABORATORIO" IS 'Numero que identifica el laboratorio';
   COMMENT ON COLUMN "SYSTEM"."LABORATORIOS"."NOMBRE_LAB" IS 'Nombre del laboratorio';
   COMMENT ON COLUMN "SYSTEM"."LABORATORIOS"."TAMA�O_LAB" IS 'Tama�o del laboratorio en metros cuadrados';
--------------------------------------------------------
--  DDL for Table MATERIAL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MATERIAL" 
   (	"ID_MATERIAL" NUMBER(3,0), 
	"NOMBRE_MATERIAL" VARCHAR2(20 BYTE), 
	"DESC_MATERIAL" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."MATERIAL"."ID_MATERIAL" IS 'Numero unico que identifica el material';
   COMMENT ON COLUMN "SYSTEM"."MATERIAL"."NOMBRE_MATERIAL" IS 'Nombre del material';
   COMMENT ON COLUMN "SYSTEM"."MATERIAL"."DESC_MATERIAL" IS 'Descripcion breve sobre el material';
--------------------------------------------------------
--  DDL for Table PATROCINADOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PATROCINADOR" 
   (	"ID_PATROCINADOR" NUMBER(15,0), 
	"NOMBRE_PATR" VARCHAR2(30 BYTE), 
	"TELEFONO_PATR" VARCHAR2(15 BYTE), 
	"CORREO_PATR" VARCHAR2(30 BYTE), 
	"ESTADO_PATR" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."PATROCINADOR"."ID_PATROCINADOR" IS 'N�mero �nico que identifica un patrocinador de otro. ';
   COMMENT ON COLUMN "SYSTEM"."PATROCINADOR"."NOMBRE_PATR" IS 'Nombre de la empresa. ';
   COMMENT ON COLUMN "SYSTEM"."PATROCINADOR"."TELEFONO_PATR" IS 'Tel�fono de la empresa. ';
   COMMENT ON COLUMN "SYSTEM"."PATROCINADOR"."CORREO_PATR" IS 'Correo electr�nico de la empresa. ';
   COMMENT ON COLUMN "SYSTEM"."PATROCINADOR"."ESTADO_PATR" IS 'Estado del patrocinador. Puede tomar los siguientes valores: activo o inactivo. ';
--------------------------------------------------------
--  DDL for Table PERSONAL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PERSONAL" 
   (	"IDENTIFICACION" NUMBER(15,0), 
	"ID_SUBSISTEMA" NUMBER(15,0), 
	"NOMBRE_PERS" VARCHAR2(30 BYTE), 
	"TELEFONO_PERS" VARCHAR2(15 BYTE), 
	"CORREO_PERS" VARCHAR2(30 BYTE), 
	"ESTADO_PERS" VARCHAR2(15 BYTE), 
	"SALARIO_PERS" NUMBER(8,0), 
	"ID_PROFESION" NUMBER(15,0), 
	"ID_EPS" NUMBER(15,0), 
	"TIPO_SANGRE" NUMBER(15,0), 
	"ID_TIPOPERSONA" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."IDENTIFICACION" IS 'N�mero de identificaci�n �nico de la persona.  ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."ID_SUBSISTEMA" IS 'N�mero que identifica un subsitema de otro dentro del proyecto. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."NOMBRE_PERS" IS 'Nombre completo de la persona. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."TELEFONO_PERS" IS 'N�mero de tel�fono celular de la persona. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."CORREO_PERS" IS 'Correo electr�nico de la persona. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."ESTADO_PERS" IS 'Estado de la persona. Puede tomar los siguientes valores: activa o inactiva ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."SALARIO_PERS" IS 'Pago. Cantidad en pesos colombianos ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."ID_PROFESION" IS 'Pregrado del estudiante o profesi�n de la cual se gradu�. ';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."ID_EPS" IS 'Numero que identifica la eps de la persona';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."TIPO_SANGRE" IS 'Numero que identifica el tipo de sangre de la persona';
   COMMENT ON COLUMN "SYSTEM"."PERSONAL"."ID_TIPOPERSONA" IS 'Numero que identifica el tipo de persona  que puede entrar al proyecto';
--------------------------------------------------------
--  DDL for Table PROFESION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PROFESION" 
   (	"ID_PROFESION" NUMBER(15,0), 
	"NOMBRE_PROFESION" VARCHAR2(50 BYTE), 
	"DESC_PROFESION" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."PROFESION"."ID_PROFESION" IS 'Numero unico que identifica la profesion';
   COMMENT ON COLUMN "SYSTEM"."PROFESION"."NOMBRE_PROFESION" IS 'Nombre de la profesion';
   COMMENT ON COLUMN "SYSTEM"."PROFESION"."DESC_PROFESION" IS 'Descripcion breve sobre la  profesion';
--------------------------------------------------------
--  DDL for Table SUBSISTEMA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUBSISTEMA" 
   (	"ID_SUBSISTEMA" NUMBER(15,0), 
	"ID_CARRO" NUMBER(15,0), 
	"NOMBRE_SUBS" VARCHAR2(30 BYTE), 
	"ESTADO_SUBS" VARCHAR2(15 BYTE), 
	"ID_LABORATORIO" NUMBER(15,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."ID_SUBSISTEMA" IS 'N�mero que identifica un subsitema de otro dentro del proyecto';
   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."ID_CARRO" IS 'N�mero que identifica el carro dentro del proyecto.';
   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."NOMBRE_SUBS" IS 'Nombre del subsistema ';
   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."ESTADO_SUBS" IS 'Estado del subsitema. Puede tomar los siguientes valores: activo o inactivo. ';
   COMMENT ON COLUMN "SYSTEM"."SUBSISTEMA"."ID_LABORATORIO" IS 'Numero que identifica los diferentes tipos de laboratorios dentro de la universidad EAFIT a los que el proyecto tiene acceso';
--------------------------------------------------------
--  DDL for Table TIPO_MONEDA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIPO_MONEDA" 
   (	"ID_TIPOMONEDA" VARCHAR2(3 BYTE), 
	"NOMBRE_TIPOMONEDA" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TIPO_MONEDA"."ID_TIPOMONEDA" IS 'Codigo de 3 letras para identificar cada divisa en base a la norma ISO 4247';
   COMMENT ON COLUMN "SYSTEM"."TIPO_MONEDA"."NOMBRE_TIPOMONEDA" IS 'Nombre completo del tipo de moneda';
--------------------------------------------------------
--  DDL for Table TIPO_PERSONA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIPO_PERSONA" 
   (	"ID_TIPOPERSONA" NUMBER(1,0), 
	"NOMB_TIPOPERSONA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TIPO_PERSONA"."ID_TIPOPERSONA" IS 'Numero unico que identifica el itpo de persona';
   COMMENT ON COLUMN "SYSTEM"."TIPO_PERSONA"."NOMB_TIPOPERSONA" IS 'Nombre del tipo de la persona';
--------------------------------------------------------
--  DDL for Table TIPO_SANGRE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIPO_SANGRE" 
   (	"ID_SANGRE" NUMBER(15,0), 
	"GS" VARCHAR2(20 BYTE), 
	"RH" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TIPO_SANGRE"."ID_SANGRE" IS 'Numero que identifica cada tipo de sangre';
   COMMENT ON COLUMN "SYSTEM"."TIPO_SANGRE"."GS" IS 'Grupo sanguineo';
   COMMENT ON COLUMN "SYSTEM"."TIPO_SANGRE"."RH" IS 'Factor RH';
--------------------------------------------------------
--  DDL for View VISTA_MATERIALES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VISTA_MATERIALES" ("ID_DONMATERIAL", "NOMBRE_MATERIAL", "CANTIDAD_MAT", "NOMBRE_SUBS", "FECHA_DONMAT") AS 
  select Donacion_material.ID_DONMATERIAL, Material.nombre_material,Donacion_material.cantidad_mat,Subsistema.nombre_subs, Donacion_material.fecha_donmat 
from Donacion_material, Material, subsistema 
Where Donacion_material.ID_DONMATERIAL = Material.ID_MATERIAL 
AND Donacion_material.ID_SUBSISTEMA = subsistema.ID_SUBSISTEMA;
--------------------------------------------------------
--  DDL for View VISTA_MONETARIAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VISTA_MONETARIAS" ("ID_MONETARIA", "NOMBRE_PATR", "NOMBRE_CARRO", "CANTIDAD_COP", "FECHA_MONE") AS 
  select donacion_monetaria.id_monetaria, Patrocinador.nombre_patr, Carrosolar.nombre_carro, Donacion_monetaria.cantidad_cop, Donacion_monetaria.fecha_mone
from DONACION_MONETARIA, CARROSOLAR, PATROCINADOR
Where DONACION_MONETARIA.ID_CARRO = CARROSOLAR.ID_CARRO
AND DONACION_MONETARIA.ID_PATROCINADOR = PATROCINADOR.ID_PATROCINADOR;
REM INSERTING into SYSTEM.CARROSOLAR
SET DEFINE OFF;
Insert into SYSTEM.CARROSOLAR (ID_CARRO,NOMBRE_CARRO,PLACA_CARRO,ESTADO_CARRO) values ('1','PRIMAVERA 1','SUN04','ACTIVO');
Insert into SYSTEM.CARROSOLAR (ID_CARRO,NOMBRE_CARRO,PLACA_CARRO,ESTADO_CARRO) values ('2','PRIMAVERA 2','SUN05','ACTIVO');
Insert into SYSTEM.CARROSOLAR (ID_CARRO,NOMBRE_CARRO,PLACA_CARRO,ESTADO_CARRO) values ('3','PRIMAVERA 3','SUN06','INACTIVO');
Insert into SYSTEM.CARROSOLAR (ID_CARRO,NOMBRE_CARRO,PLACA_CARRO,ESTADO_CARRO) values ('5','Trigger funciono','SOL91','ACTIVO');
Insert into SYSTEM.CARROSOLAR (ID_CARRO,NOMBRE_CARRO,PLACA_CARRO,ESTADO_CARRO) values ('4','funciono','sfsdf','ACTIVO');
REM INSERTING into SYSTEM.DONACION_MATERIAL
SET DEFINE OFF;
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('1','7','103','1000',to_date('23/07/15','DD/MM/RR'),'3');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('2','7','203','1200',to_date('16/09/15','DD/MM/RR'),'4');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('3','3','105','200',to_date('13/02/14','DD/MM/RR'),'2');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('4','3','205','250',to_date('12/03/15','DD/MM/RR'),'7');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('5','4','102','5',to_date('24/01/14','DD/MM/RR'),'7');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('6','4','202','10',to_date('20/10/14','DD/MM/RR'),'3');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('7','6','101','30',to_date('12/03/14','DD/MM/RR'),'4');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('8','6','201','35',to_date('15/07/15','DD/MM/RR'),'2');
Insert into SYSTEM.DONACION_MATERIAL (ID_DONMATERIAL,ID_PATROCINADOR,ID_SUBSISTEMA,CANTIDAD_MAT,FECHA_DONMAT,ID_MATERIAL) values ('9','6','102','1',to_date('12/11/16','DD/MM/RR'),'3');
REM INSERTING into SYSTEM.DONACION_MONETARIA
SET DEFINE OFF;
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('1','2','2','1000000000',to_date('30/04/15','DD/MM/RR'),'COP','1','1000000000');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('2','1','2','1200000000',to_date('20/03/15','DD/MM/RR'),'COP','1','1200000000');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('3','5','2','10000',to_date('23/05/15','DD/MM/RR'),'USD','2500','25000600');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('4','2','1','500000000',to_date('28/01/14','DD/MM/RR'),'COP','1','500000000');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('5','1','1','10000',to_date('14/01/14','DD/MM/RR'),'COP','25000','25000000');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('6','5','1','5000',to_date('21/08/14','DD/MM/RR'),'USD','2800','14000600');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('8','5','2','53656456456',to_date('12/12/12','DD/MM/RR'),'GBP','324','234324');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('9','7','3','2000',to_date('15/12/16','DD/MM/RR'),'AUD','5','10000');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('10','2','3','10',to_date('04/05/16','DD/MM/RR'),'SEK','20','30');
Insert into SYSTEM.DONACION_MONETARIA (ID_MONETARIA,ID_PATROCINADOR,ID_CARRO,CANTIDAD_MONE_ORIGINAL,FECHA_MONE,ID_TIPOMONEDA,TASA_CAMBIO,CANTIDAD_COP) values ('7','3','3','10000000',to_date('12/11/16','DD/MM/RR'),'COP','1','10000000');
REM INSERTING into SYSTEM.EPS
SET DEFINE OFF;
Insert into SYSTEM.EPS (ID_EPS,NOMBRE_EPS,TELEFONO_EPS,CIUDAD_EPS) values ('1','SURA','2346532','MEDELLIN');
Insert into SYSTEM.EPS (ID_EPS,NOMBRE_EPS,TELEFONO_EPS,CIUDAD_EPS) values ('2','SURA','2346532','MEDELLIN');
Insert into SYSTEM.EPS (ID_EPS,NOMBRE_EPS,TELEFONO_EPS,CIUDAD_EPS) values ('3','COOMEVA','7692341','MEDELLIN');
Insert into SYSTEM.EPS (ID_EPS,NOMBRE_EPS,TELEFONO_EPS,CIUDAD_EPS) values ('4','COOMEVA','4326489','MEDELLIN');
Insert into SYSTEM.EPS (ID_EPS,NOMBRE_EPS,TELEFONO_EPS,CIUDAD_EPS) values ('5','NUEVA EPS','3314563','MEDELLIN');
Insert into SYSTEM.EPS (ID_EPS,NOMBRE_EPS,TELEFONO_EPS,CIUDAD_EPS) values ('6','SALUDCOOP','3325487','MEDELLIN');
Insert into SYSTEM.EPS (ID_EPS,NOMBRE_EPS,TELEFONO_EPS,CIUDAD_EPS) values ('7','COMFENALCO','7684532','MEDELLIN');
REM INSERTING into SYSTEM.GASTOS
SET DEFINE OFF;
Insert into SYSTEM.GASTOS (ID_GASTO,ID_CARRO,CANTIDAD_GASTO,DESC_GASTO,FECHA_GASTO) values ('1','1','25000000','PANELES SOLARES',to_date('23/05/14','DD/MM/RR'));
Insert into SYSTEM.GASTOS (ID_GASTO,ID_CARRO,CANTIDAD_GASTO,DESC_GASTO,FECHA_GASTO) values ('2','2','30000000','PANELES SOLARES',to_date('11/02/15','DD/MM/RR'));
Insert into SYSTEM.GASTOS (ID_GASTO,ID_CARRO,CANTIDAD_GASTO,DESC_GASTO,FECHA_GASTO) values ('3','2','5000000','LLANTAS',to_date('05/04/16','DD/MM/RR'));
Insert into SYSTEM.GASTOS (ID_GASTO,ID_CARRO,CANTIDAD_GASTO,DESC_GASTO,FECHA_GASTO) values ('4','2','20000000','BATERIA',to_date('07/01/15','DD/MM/RR'));
Insert into SYSTEM.GASTOS (ID_GASTO,ID_CARRO,CANTIDAD_GASTO,DESC_GASTO,FECHA_GASTO) values ('5','1','15000000','BATERIA',to_date('10/05/14','DD/MM/RR'));
Insert into SYSTEM.GASTOS (ID_GASTO,ID_CARRO,CANTIDAD_GASTO,DESC_GASTO,FECHA_GASTO) values ('6','1','3000000','LLANTAS',to_date('23/09/16','DD/MM/RR'));
Insert into SYSTEM.GASTOS (ID_GASTO,ID_CARRO,CANTIDAD_GASTO,DESC_GASTO,FECHA_GASTO) values ('7','5','23443','sdfd',to_date('12/01/11','DD/MM/RR'));
REM INSERTING into SYSTEM.LABORATORIOS
SET DEFINE OFF;
Insert into SYSTEM.LABORATORIOS (ID_LABORATORIO,NOMBRE_LAB,"TAMA�O_LAB") values ('1','MATERIALES','110');
Insert into SYSTEM.LABORATORIOS (ID_LABORATORIO,NOMBRE_LAB,"TAMA�O_LAB") values ('2','MADERA','120');
Insert into SYSTEM.LABORATORIOS (ID_LABORATORIO,NOMBRE_LAB,"TAMA�O_LAB") values ('3','ELECTRONICA','50');
Insert into SYSTEM.LABORATORIOS (ID_LABORATORIO,NOMBRE_LAB,"TAMA�O_LAB") values ('4','SOLDADURA','60');
Insert into SYSTEM.LABORATORIOS (ID_LABORATORIO,NOMBRE_LAB,"TAMA�O_LAB") values ('5','INFORMATICA','100');
Insert into SYSTEM.LABORATORIOS (ID_LABORATORIO,NOMBRE_LAB,"TAMA�O_LAB") values ('6','Pruebassss','10');
REM INSERTING into SYSTEM.MATERIAL
SET DEFINE OFF;
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('1','PANEL SOLA','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('2','MOTOR','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('3','BATERIA','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('4','LLANTA','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('5','CPPTS','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('6','PANTALLA','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('7','LED','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('8','SELLANTE','...');
Insert into SYSTEM.MATERIAL (ID_MATERIAL,NOMBRE_MATERIAL,DESC_MATERIAL) values ('9','MOLDE','...');
REM INSERTING into SYSTEM.PATROCINADOR
SET DEFINE OFF;
Insert into SYSTEM.PATROCINADOR (ID_PATROCINADOR,NOMBRE_PATR,TELEFONO_PATR,CORREO_PATR,ESTADO_PATR) values ('1','EAFIT','4489500','ADMIN@EAFIT.EDU.CO','ACTIVO');
Insert into SYSTEM.PATROCINADOR (ID_PATROCINADOR,NOMBRE_PATR,TELEFONO_PATR,CORREO_PATR,ESTADO_PATR) values ('2','EPM','4444115','ADMIN@EPM.COM.CO','ACTIVO');
Insert into SYSTEM.PATROCINADOR (ID_PATROCINADOR,NOMBRE_PATR,TELEFONO_PATR,CORREO_PATR,ESTADO_PATR) values ('3','HYBRYTEC','4440520','ADMIN@HYBRYTEC.COM','ACTIVO');
Insert into SYSTEM.PATROCINADOR (ID_PATROCINADOR,NOMBRE_PATR,TELEFONO_PATR,CORREO_PATR,ESTADO_PATR) values ('4','MOLDES MEDELLIN','3700190','ADMIN@MOLDESMEDELLIN.COM','ACTIVO');
Insert into SYSTEM.PATROCINADOR (ID_PATROCINADOR,NOMBRE_PATR,TELEFONO_PATR,CORREO_PATR,ESTADO_PATR) values ('5','ADDICT','2658104','ADMIN@ADDICT.COM','ACTIVO');
Insert into SYSTEM.PATROCINADOR (ID_PATROCINADOR,NOMBRE_PATR,TELEFONO_PATR,CORREO_PATR,ESTADO_PATR) values ('6','ANDERCOL','4700700','ADMIN@ANDERCOL.COM.CO','ACTIVO');
Insert into SYSTEM.PATROCINADOR (ID_PATROCINADOR,NOMBRE_PATR,TELEFONO_PATR,CORREO_PATR,ESTADO_PATR) values ('7','COLCIRCUITOS','4442652','ADMIN@COLCIRCUITOS.COM.CO','ACTIVO');
REM INSERTING into SYSTEM.PERSONAL
SET DEFINE OFF;
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1054337265','101','Alirio Suarez ','8596036607','ambientat@desalineeu.es','ACTIVO','0','6','1','2','1');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1087665324','102','Alejandro Jimenez ','8889321376','esculam@tenutari.gov','ACTIVO','0','7','2','3','2');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1076554324','103','Marianela Cordero ','6940353714','bolcants@acanadors.org','ACTIVO','2505080','6','4','5','2');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1035669879','103','Marcelo Camero ','605251273','amplaries@avorreixo.com','ACTIVO','0','2','2','2','4');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1023445786','105','Carmelo de Luca ','6413264062','tecs@episodiessin.gov','ACTIVO','2305080','4','5','2','2');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1098324556','201','Maria Aurora Zambrano ','6111536585','vendicio@correlessem.com','ACTIVO','0','15','2','5','3');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1043345612','202','Luis Sosa ','6938233857','portallapis@capbrevessem.org','ACTIVO','0','11','4','6','3');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1034529384','202','Jose Manuel Herrera ','7304907031','junyirem@espellassiu.eu','ACTIVO','0','20','6','1','2');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1043293471','206','Luis Manuel Villegas ','7588138112','groguejara@descurarieu.eu','ACTIVO','2305080','3','2','8','2');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('1032732341','205','Jhony Alberto S�enz Hurtado','8938815514','grunyis@erices.com','ACTIVO','2505080','3','3','3','4');
Insert into SYSTEM.PERSONAL (IDENTIFICACION,ID_SUBSISTEMA,NOMBRE_PERS,TELEFONO_PERS,CORREO_PERS,ESTADO_PERS,SALARIO_PERS,ID_PROFESION,ID_EPS,TIPO_SANGRE,ID_TIPOPERSONA) values ('234','101','sdfd','sd23','23lkjl2','ACTIVO','7423','1','1','1','1');
REM INSERTING into SYSTEM.PROFESION
SET DEFINE OFF;
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('1','ADMINISTRACION DE NEGOCIOS','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('2','NEGOCIOS INTERNACIONALES','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('3','ECONOMIA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('4','INGENIERIA DE PROCESOS','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('5','INGENIERIA DE SISTEMAS','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('6','CONTADURIA PUBLICA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('7','INGENIERIA DE PRODUCCION','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('8','INGENIERIA CIVIL','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('9','INGENIERIA MECANICA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('10','GEOLOGIA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('11','MERCADEO','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('12','INGENIERIA DE DISE�O DE PRODUCTO','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('13','MUSICA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('14','COMUNICACION SOCIAL','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('15','CIENCIAS POLITICAS','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('16','PSICOLOGIA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('17','DERECHO','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('18','FINANZAS','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('19','BIOLOGIA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('20','INGENIERIA MATEMATICA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('21','INGENIERIA FISICA','...');
Insert into SYSTEM.PROFESION (ID_PROFESION,NOMBRE_PROFESION,DESC_PROFESION) values ('22','Prueb','asdf');
REM INSERTING into SYSTEM.SUBSISTEMA
SET DEFINE OFF;
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('101','1','P1-MECANICA','ACTIVO','1');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('102','1','P1-AERODINAMICA','ACTIVO','2');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('103','1','P1-ELECTRONICA','ACTIVO','3');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('201','2','P2-MECANICA','ACTIVO','1');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('202','2','P2-AERODINAMICA','ACTIVO','2');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('203','2','P2-ELECTRONICA','ACTIVO','3');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('104','1','P1-CARROCERIA','INACTIVO','1');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('204','2','P2-CARROCERIA','INACTIVO','1');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('105','1','P1-SOLAR','ACTIVO','4');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('205','2','P2-SOLAR','ACTIVO','4');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('106','1','P1-ESTRATEGIA','ACTIVO','5');
Insert into SYSTEM.SUBSISTEMA (ID_SUBSISTEMA,ID_CARRO,NOMBRE_SUBS,ESTADO_SUBS,ID_LABORATORIO) values ('206','2','P2-ESTRATEGIA','ACTIVO','5');
REM INSERTING into SYSTEM.TIPO_MONEDA
SET DEFINE OFF;
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('COP','PESOS COLOMBIANOS');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('USD','DOLAR ESTADOUNIDENSE');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('AUD','DOLAR AUSTRALIANO');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('GBP','LIBRA ESTERLINA');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('EUR','EURO');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('JPY','YEN JAPONES');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('CHF','FRANCO SUIZO');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('CAD','DOLAR CANADIENSE');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('SEK','CORONA SUECA');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('NOK','CORONA NORUEGA');
Insert into SYSTEM.TIPO_MONEDA (ID_TIPOMONEDA,NOMBRE_TIPOMONEDA) values ('ABC','otra');
REM INSERTING into SYSTEM.TIPO_PERSONA
SET DEFINE OFF;
Insert into SYSTEM.TIPO_PERSONA (ID_TIPOPERSONA,NOMB_TIPOPERSONA) values ('1','ESTUDIANTE INTERNO');
Insert into SYSTEM.TIPO_PERSONA (ID_TIPOPERSONA,NOMB_TIPOPERSONA) values ('2','ESTUDIANTE EXTERNO');
Insert into SYSTEM.TIPO_PERSONA (ID_TIPOPERSONA,NOMB_TIPOPERSONA) values ('3','PROFESOR');
Insert into SYSTEM.TIPO_PERSONA (ID_TIPOPERSONA,NOMB_TIPOPERSONA) values ('4','PERSONA EXTERNA');
Insert into SYSTEM.TIPO_PERSONA (ID_TIPOPERSONA,NOMB_TIPOPERSONA) values ('5','Otross');
REM INSERTING into SYSTEM.TIPO_SANGRE
SET DEFINE OFF;
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('1','A','+');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('2','A','-');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('3','B','+');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('4','B','-');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('5','AB','+');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('6','AB','-');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('7','O','+');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('8','O','-');
Insert into SYSTEM.TIPO_SANGRE (ID_SANGRE,GS,RH) values ('9','pr','pr');
REM INSERTING into SYSTEM.VISTA_MATERIALES
SET DEFINE OFF;
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('7','LED','30','P1-MECANICA',to_date('12/03/14','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('9','MOLDE','1','P1-AERODINAMICA',to_date('12/11/16','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('5','CPPTS','5','P1-AERODINAMICA',to_date('24/01/14','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('1','PANEL SOLA','1000','P1-ELECTRONICA',to_date('23/07/15','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('8','SELLANTE','35','P2-MECANICA',to_date('15/07/15','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('6','PANTALLA','10','P2-AERODINAMICA',to_date('20/10/14','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('2','MOTOR','1200','P2-ELECTRONICA',to_date('16/09/15','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('3','BATERIA','200','P1-SOLAR',to_date('13/02/14','DD/MM/RR'));
Insert into SYSTEM.VISTA_MATERIALES (ID_DONMATERIAL,NOMBRE_MATERIAL,CANTIDAD_MAT,NOMBRE_SUBS,FECHA_DONMAT) values ('4','LLANTA','250','P2-SOLAR',to_date('12/03/15','DD/MM/RR'));
REM INSERTING into SYSTEM.VISTA_MONETARIAS
SET DEFINE OFF;
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('5','EAFIT','PRIMAVERA 1','25000000',to_date('14/01/14','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('2','EAFIT','PRIMAVERA 2','1200000000',to_date('20/03/15','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('10','EPM','PRIMAVERA 3','30',to_date('04/05/16','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('4','EPM','PRIMAVERA 1','500000000',to_date('28/01/14','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('1','EPM','PRIMAVERA 2','1000000000',to_date('30/04/15','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('7','HYBRYTEC','PRIMAVERA 3','10000000',to_date('12/11/16','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('8','ADDICT','PRIMAVERA 2','234324',to_date('12/12/12','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('6','ADDICT','PRIMAVERA 1','14000600',to_date('21/08/14','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('3','ADDICT','PRIMAVERA 2','25000600',to_date('23/05/15','DD/MM/RR'));
Insert into SYSTEM.VISTA_MONETARIAS (ID_MONETARIA,NOMBRE_PATR,NOMBRE_CARRO,CANTIDAD_COP,FECHA_MONE) values ('9','COLCIRCUITOS','PRIMAVERA 3','10000',to_date('15/12/16','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index CARROSOLAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CARROSOLAR_PK" ON "SYSTEM"."CARROSOLAR" ("ID_CARRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DONACION_MATERIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DONACION_MATERIAL_PK" ON "SYSTEM"."DONACION_MATERIAL" ("ID_DONMATERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DONACION_MONETARIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DONACION_MONETARIA_PK" ON "SYSTEM"."DONACION_MONETARIA" ("ID_MONETARIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EPS_PK" ON "SYSTEM"."EPS" ("ID_EPS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GASTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GASTOS_PK" ON "SYSTEM"."GASTOS" ("ID_GASTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABORATORIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LABORATORIOS_PK" ON "SYSTEM"."LABORATORIOS" ("ID_LABORATORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MATERIAL_PK" ON "SYSTEM"."MATERIAL" ("ID_MATERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATROCINADOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PATROCINADOR_PK" ON "SYSTEM"."PATROCINADOR" ("ID_PATROCINADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PERSONAL_PK" ON "SYSTEM"."PERSONAL" ("IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PROFESION_PK" ON "SYSTEM"."PROFESION" ("ID_PROFESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUBSISTEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SUBSISTEMA_PK" ON "SYSTEM"."SUBSISTEMA" ("ID_SUBSISTEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_MONEDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_MONEDA_PK" ON "SYSTEM"."TIPO_MONEDA" ("ID_TIPOMONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_PERSONA_PK" ON "SYSTEM"."TIPO_PERSONA" ("ID_TIPOPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_SANGRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_SANGRE_PK" ON "SYSTEM"."TIPO_SANGRE" ("ID_SANGRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CARROSOLAR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CARROSOLAR" ADD CONSTRAINT "CARROSOLAR_CHK_ESTADO" CHECK ("ESTADO_CARRO"='ACTIVO' OR "ESTADO_CARRO"='INACTIVO') ENABLE;
  ALTER TABLE "SYSTEM"."CARROSOLAR" ADD CONSTRAINT "CARROSOLAR_PK" PRIMARY KEY ("ID_CARRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("ESTADO_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("PLACA_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("NOMBRE_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARROSOLAR" MODIFY ("ID_CARRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DONACION_MATERIAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" MODIFY ("FECHA_DONMAT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" ADD CONSTRAINT "DONACION_MATERIAL_PK" PRIMARY KEY ("ID_DONMATERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" MODIFY ("CANTIDAD_MAT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" MODIFY ("ID_SUBSISTEMA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" MODIFY ("ID_PATROCINADOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" MODIFY ("ID_DONMATERIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DONACION_MONETARIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("CANTIDAD_COP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("TASA_CAMBIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("ID_TIPOMONEDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("FECHA_MONE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" ADD CONSTRAINT "DONACION_MONETARIA_PK" PRIMARY KEY ("ID_MONETARIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("CANTIDAD_MONE_ORIGINAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("ID_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("ID_PATROCINADOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" MODIFY ("ID_MONETARIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EPS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EPS" ADD CONSTRAINT "EPS_PK" PRIMARY KEY ("ID_EPS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EPS" MODIFY ("CIUDAD_EPS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EPS" MODIFY ("TELEFONO_EPS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EPS" MODIFY ("NOMBRE_EPS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EPS" MODIFY ("ID_EPS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GASTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GASTOS" ADD CONSTRAINT "GASTOS_PK" PRIMARY KEY ("ID_GASTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GASTOS" MODIFY ("FECHA_GASTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GASTOS" MODIFY ("DESC_GASTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GASTOS" MODIFY ("CANTIDAD_GASTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GASTOS" MODIFY ("ID_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GASTOS" MODIFY ("ID_GASTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABORATORIOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LABORATORIOS" ADD CONSTRAINT "LABORATORIOS_PK" PRIMARY KEY ("ID_LABORATORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."LABORATORIOS" MODIFY ("TAMA�O_LAB" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LABORATORIOS" MODIFY ("NOMBRE_LAB" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LABORATORIOS" MODIFY ("ID_LABORATORIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MATERIAL" ADD CONSTRAINT "MATERIAL_PK" PRIMARY KEY ("ID_MATERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MATERIAL" MODIFY ("DESC_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATERIAL" MODIFY ("NOMBRE_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATERIAL" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATROCINADOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATROCINADOR" MODIFY ("TELEFONO_PATR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PATROCINADOR" ADD CONSTRAINT "PATROCINADOR_CHK_ESTADO" CHECK ("ESTADO_PATR"='ACTIVO' OR "ESTADO_PATR"='INACTIVO') ENABLE;
  ALTER TABLE "SYSTEM"."PATROCINADOR" ADD CONSTRAINT "PATROCINADOR_PK" PRIMARY KEY ("ID_PATROCINADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PATROCINADOR" MODIFY ("ESTADO_PATR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PATROCINADOR" MODIFY ("CORREO_PATR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PATROCINADOR" MODIFY ("NOMBRE_PATR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PATROCINADOR" MODIFY ("ID_PATROCINADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("TIPO_SANGRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("ID_EPS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_CHK_ESTADO" CHECK ("ESTADO_PERS"='ACTIVO' OR "ESTADO_PERS"='INACTIVO') ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_PK" PRIMARY KEY ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("ID_PROFESION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("SALARIO_PERS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("ESTADO_PERS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("ID_TIPOPERSONA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("CORREO_PERS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("TELEFONO_PERS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("NOMBRE_PERS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("ID_SUBSISTEMA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONAL" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROFESION" ADD CONSTRAINT "PROFESION_PK" PRIMARY KEY ("ID_PROFESION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PROFESION" MODIFY ("DESC_PROFESION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFESION" MODIFY ("NOMBRE_PROFESION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFESION" MODIFY ("ID_PROFESION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSISTEMA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("ID_LABORATORIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("ESTADO_SUBS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSISTEMA" ADD CONSTRAINT "SUBSISTEMA_CHK_ESTADO" CHECK ("ESTADO_SUBS"='ACTIVO' OR "ESTADO_SUBS"='INACTIVO') ENABLE;
  ALTER TABLE "SYSTEM"."SUBSISTEMA" ADD CONSTRAINT "SUBSISTEMA_PK" PRIMARY KEY ("ID_SUBSISTEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("NOMBRE_SUBS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("ID_CARRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSISTEMA" MODIFY ("ID_SUBSISTEMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_MONEDA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIPO_MONEDA" ADD CONSTRAINT "TIPO_MONEDA_PK" PRIMARY KEY ("ID_TIPOMONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TIPO_MONEDA" MODIFY ("NOMBRE_TIPOMONEDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIPO_MONEDA" MODIFY ("ID_TIPOMONEDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_PERSONA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIPO_PERSONA" ADD CONSTRAINT "TIPO_PERSONA_PK" PRIMARY KEY ("ID_TIPOPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TIPO_PERSONA" MODIFY ("NOMB_TIPOPERSONA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIPO_PERSONA" MODIFY ("ID_TIPOPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_SANGRE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIPO_SANGRE" ADD CONSTRAINT "TIPO_SANGRE_PK" PRIMARY KEY ("ID_SANGRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TIPO_SANGRE" MODIFY ("RH" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIPO_SANGRE" MODIFY ("GS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TIPO_SANGRE" MODIFY ("ID_SANGRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DONACION_MATERIAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" ADD CONSTRAINT "DONACION_MATERIAL_FK1" FOREIGN KEY ("ID_PATROCINADOR")
	  REFERENCES "SYSTEM"."PATROCINADOR" ("ID_PATROCINADOR") ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" ADD CONSTRAINT "DONACION_MATERIAL_FK2" FOREIGN KEY ("ID_SUBSISTEMA")
	  REFERENCES "SYSTEM"."SUBSISTEMA" ("ID_SUBSISTEMA") ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MATERIAL" ADD CONSTRAINT "DONACION_MATERIAL_FK3" FOREIGN KEY ("ID_MATERIAL")
	  REFERENCES "SYSTEM"."MATERIAL" ("ID_MATERIAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DONACION_MONETARIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" ADD CONSTRAINT "DONACION_MONETARIA_FK1" FOREIGN KEY ("ID_PATROCINADOR")
	  REFERENCES "SYSTEM"."PATROCINADOR" ("ID_PATROCINADOR") ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" ADD CONSTRAINT "DONACION_MONETARIA_FK2" FOREIGN KEY ("ID_CARRO")
	  REFERENCES "SYSTEM"."CARROSOLAR" ("ID_CARRO") ENABLE;
  ALTER TABLE "SYSTEM"."DONACION_MONETARIA" ADD CONSTRAINT "DONACION_MONETARIA_FK3" FOREIGN KEY ("ID_TIPOMONEDA")
	  REFERENCES "SYSTEM"."TIPO_MONEDA" ("ID_TIPOMONEDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GASTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GASTOS" ADD CONSTRAINT "GASTOS_FK1" FOREIGN KEY ("ID_CARRO")
	  REFERENCES "SYSTEM"."CARROSOLAR" ("ID_CARRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_FK1" FOREIGN KEY ("ID_PROFESION")
	  REFERENCES "SYSTEM"."PROFESION" ("ID_PROFESION") ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_FK2" FOREIGN KEY ("ID_EPS")
	  REFERENCES "SYSTEM"."EPS" ("ID_EPS") ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_FK3" FOREIGN KEY ("TIPO_SANGRE")
	  REFERENCES "SYSTEM"."TIPO_SANGRE" ("ID_SANGRE") ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERSONAL_FK4" FOREIGN KEY ("ID_TIPOPERSONA")
	  REFERENCES "SYSTEM"."TIPO_PERSONA" ("ID_TIPOPERSONA") ENABLE;
  ALTER TABLE "SYSTEM"."PERSONAL" ADD CONSTRAINT "PERTENECE_FK" FOREIGN KEY ("ID_SUBSISTEMA")
	  REFERENCES "SYSTEM"."SUBSISTEMA" ("ID_SUBSISTEMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSISTEMA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSISTEMA" ADD CONSTRAINT "SUBSISTEMA_FK1" FOREIGN KEY ("ID_LABORATORIO")
	  REFERENCES "SYSTEM"."LABORATORIOS" ("ID_LABORATORIO") ENABLE;
  ALTER TABLE "SYSTEM"."SUBSISTEMA" ADD CONSTRAINT "SUBSISTEMA_FK2" FOREIGN KEY ("ID_CARRO")
	  REFERENCES "SYSTEM"."CARROSOLAR" ("ID_CARRO") ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUMENTO_POR_CARRO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."AUMENTO_POR_CARRO" 
AFTER INSERT ON CARROSOLAR 
FOR EACH ROW 
BEGIN
  AUMENTO('100');
END;
/
ALTER TRIGGER "SYSTEM"."AUMENTO_POR_CARRO" ENABLE;
--------------------------------------------------------
--  DDL for Procedure AUMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "SYSTEM"."AUMENTO" 
(
  cantidad IN NUMBER
)
AS 
  CURSOR CURS_AUM 
  IS
  SELECT PERSONAL.SALARIO_PERS 
  FROM PERSONAL
  WHERE PERSONAL.SALARIO_PERS > 0
  FOR UPDATE;
  salario NUMBER(8);
BEGIN
  OPEN CURS_AUM;
  FETCH CURS_AUM INTO salario;
  WHILE CURS_AUM%found
  LOOP 
	UPDATE PERSONAL 
        SET SALARIO_PERS = salario+cantidad
        WHERE CURRENT OF CURS_AUM;

        FETCH CURS_AUM INTO salario;
    END LOOP; 
  CLOSE CURS_AUM;
  
END AUMENTO;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_CARRO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "SYSTEM"."UPDATE_CARRO" 
(
  NOMBRE IN VARCHAR2 
, ID IN NUMBER
) AS 
BEGIN
  UPDATE CARROSOLAR SET NOMBRE_CARRO = NOMBRE WHERE ID_CARRO = ID;
  COMMIT;
END UPDATE_CARRO;

/