/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

/**
 *
 * @author Daniel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("--PRIMAVERA--MENU PRINCIPAL--");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        divisasButton = new javax.swing.JButton();
        carrosSolaresButton = new javax.swing.JButton();
        profesionesButton = new javax.swing.JButton();
        epsButton = new javax.swing.JButton();
        tipoDeSangreButton = new javax.swing.JButton();
        laboratoriosButton = new javax.swing.JButton();
        patrocinadoresButton = new javax.swing.JButton();
        subsistemasButton = new javax.swing.JButton();
        tipoDePersonaButton = new javax.swing.JButton();
        materialesButton = new javax.swing.JButton();
        personalButton = new javax.swing.JButton();
        donacionesMonetariasButton = new javax.swing.JButton();
        donacionesMaterialesButton = new javax.swing.JButton();
        gastosButton = new javax.swing.JButton();
        ingresoDePersonalButton = new javax.swing.JButton();
        donacionesButton = new javax.swing.JButton();
        consultarMaterialesButton = new javax.swing.JButton();
        consultarGastosButton = new javax.swing.JButton();
        clasificacionPatrocinadoresButton = new javax.swing.JButton();
        consultaPorProfesionButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        consultaPorProfesionButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CarroConLogo90.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Consultar.png"))); // NOI18N

        divisasButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        divisasButton.setText("Divisas");
        divisasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisasButtonActionPerformed(evt);
            }
        });

        carrosSolaresButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        carrosSolaresButton.setText("Carros solares");
        carrosSolaresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrosSolaresButtonActionPerformed(evt);
            }
        });

        profesionesButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        profesionesButton.setText("Profesiones");
        profesionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionesButtonActionPerformed(evt);
            }
        });

        epsButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        epsButton.setText("EPS");
        epsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epsButtonActionPerformed(evt);
            }
        });

        tipoDeSangreButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipoDeSangreButton.setText("Tipos de sangre");
        tipoDeSangreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeSangreButtonActionPerformed(evt);
            }
        });

        laboratoriosButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        laboratoriosButton.setText("Laboratorios");
        laboratoriosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratoriosButtonActionPerformed(evt);
            }
        });

        patrocinadoresButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        patrocinadoresButton.setText("Patrocinadores");
        patrocinadoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patrocinadoresButtonActionPerformed(evt);
            }
        });

        subsistemasButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        subsistemasButton.setText("Subsistemas");
        subsistemasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsistemasButtonActionPerformed(evt);
            }
        });

        tipoDePersonaButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipoDePersonaButton.setText("Tipos de persona");
        tipoDePersonaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDePersonaButtonActionPerformed(evt);
            }
        });

        materialesButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        materialesButton.setText("Materiales");
        materialesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialesButtonActionPerformed(evt);
            }
        });

        personalButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        personalButton.setText("Personal");
        personalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalButtonActionPerformed(evt);
            }
        });

        donacionesMonetariasButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        donacionesMonetariasButton.setText("Donaciones monetarias");
        donacionesMonetariasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donacionesMonetariasButtonActionPerformed(evt);
            }
        });

        donacionesMaterialesButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        donacionesMaterialesButton.setText("Donaciones materiales");
        donacionesMaterialesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donacionesMaterialesButtonActionPerformed(evt);
            }
        });

        gastosButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        gastosButton.setText("Gastos");
        gastosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosButtonActionPerformed(evt);
            }
        });

        ingresoDePersonalButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ingresoDePersonalButton.setText("Ingreso de personal");
        ingresoDePersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDePersonalButtonActionPerformed(evt);
            }
        });

        donacionesButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        donacionesButton.setText("Donaciones");
        donacionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donacionesButtonActionPerformed(evt);
            }
        });

        consultarMaterialesButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        consultarMaterialesButton.setText("Materiales");
        consultarMaterialesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMaterialesButtonActionPerformed(evt);
            }
        });

        consultarGastosButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        consultarGastosButton.setText("Gastos");
        consultarGastosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarGastosButtonActionPerformed(evt);
            }
        });

        clasificacionPatrocinadoresButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        clasificacionPatrocinadoresButton.setText("Clasificacion de patrocinadores");
        clasificacionPatrocinadoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionPatrocinadoresButtonActionPerformed(evt);
            }
        });

        consultaPorProfesionButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        consultaPorProfesionButton.setText("Consulta por profesión");
        consultaPorProfesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPorProfesionButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gestionar.png"))); // NOI18N

        consultaPorProfesionButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        consultaPorProfesionButton1.setText("Salir");
        consultaPorProfesionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPorProfesionButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(donacionesMaterialesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoDePersonaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patrocinadoresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoDeSangreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subsistemasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carrosSolaresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(donacionesMonetariasButton, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(laboratoriosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(profesionesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gastosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(materialesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(divisasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(epsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(donacionesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarMaterialesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarGastosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clasificacionPatrocinadoresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaPorProfesionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresoDePersonalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaPorProfesionButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laboratoriosButton)
                            .addComponent(donacionesMonetariasButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(donacionesMaterialesButton)
                            .addComponent(profesionesButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoDePersonaButton)
                            .addComponent(gastosButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(materialesButton)
                            .addComponent(patrocinadoresButton))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoDeSangreButton)
                            .addComponent(divisasButton))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subsistemasButton)
                            .addComponent(personalButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ingresoDePersonalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(donacionesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultarMaterialesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultarGastosButton)
                        .addGap(14, 14, 14)
                        .addComponent(clasificacionPatrocinadoresButton)
                        .addGap(11, 11, 11)
                        .addComponent(consultaPorProfesionButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carrosSolaresButton)
                        .addComponent(epsButton))
                    .addComponent(consultaPorProfesionButton1))
                .addGap(204, 204, 204))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaPorProfesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPorProfesionButtonActionPerformed
        ConsultaPorProfesion vent = new ConsultaPorProfesion();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_consultaPorProfesionButtonActionPerformed

    private void clasificacionPatrocinadoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionPatrocinadoresButtonActionPerformed
        ClasificacionDePatrocinadores vent = new ClasificacionDePatrocinadores();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_clasificacionPatrocinadoresButtonActionPerformed

    private void consultarGastosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarGastosButtonActionPerformed
        Gastos vent = new Gastos();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_consultarGastosButtonActionPerformed

    private void consultarMaterialesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMaterialesButtonActionPerformed
        Materiales vent = new Materiales();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_consultarMaterialesButtonActionPerformed

    private void donacionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donacionesButtonActionPerformed
        Donaciones vent = new Donaciones();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_donacionesButtonActionPerformed

    private void ingresoDePersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDePersonalButtonActionPerformed
        ConsultarIngresoPersonal vent = new ConsultarIngresoPersonal();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_ingresoDePersonalButtonActionPerformed

    private void gastosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosButtonActionPerformed
        GestionarGastos vent = new GestionarGastos();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_gastosButtonActionPerformed

    private void donacionesMaterialesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donacionesMaterialesButtonActionPerformed
        GestionarDonacionMaterial vent = new GestionarDonacionMaterial();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_donacionesMaterialesButtonActionPerformed

    private void donacionesMonetariasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donacionesMonetariasButtonActionPerformed
        GestionarDonacionMonetaria vent = new GestionarDonacionMonetaria();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_donacionesMonetariasButtonActionPerformed

    private void personalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalButtonActionPerformed
        GestionarPersonal vent = new GestionarPersonal();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_personalButtonActionPerformed

    private void materialesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialesButtonActionPerformed
        GestionarMateriales vent = new GestionarMateriales();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_materialesButtonActionPerformed

    private void tipoDePersonaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDePersonaButtonActionPerformed
        GestionarTiposDePersonas vent = new GestionarTiposDePersonas();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_tipoDePersonaButtonActionPerformed

    private void subsistemasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsistemasButtonActionPerformed
        GestionarSubsistemas vent = new GestionarSubsistemas();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_subsistemasButtonActionPerformed

    private void patrocinadoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrocinadoresButtonActionPerformed
        GestionarPatrocinadores vent = new GestionarPatrocinadores();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_patrocinadoresButtonActionPerformed

    private void laboratoriosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratoriosButtonActionPerformed
        GestionarLaboratorios vent = new GestionarLaboratorios();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_laboratoriosButtonActionPerformed

    private void tipoDeSangreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeSangreButtonActionPerformed
        GestionarTiposDeSangre vent = new GestionarTiposDeSangre();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_tipoDeSangreButtonActionPerformed

    private void epsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epsButtonActionPerformed
        GestionarEPS vent = new GestionarEPS();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_epsButtonActionPerformed

    private void profesionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionesButtonActionPerformed
        GestionarProfesiones vent = new GestionarProfesiones();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_profesionesButtonActionPerformed

    private void carrosSolaresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrosSolaresButtonActionPerformed
        GestionarCarroSolar vent = new GestionarCarroSolar();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_carrosSolaresButtonActionPerformed

    private void divisasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisasButtonActionPerformed
        GestionarDivisas vent = new GestionarDivisas();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_divisasButtonActionPerformed

    private void consultaPorProfesionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPorProfesionButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_consultaPorProfesionButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carrosSolaresButton;
    private javax.swing.JButton clasificacionPatrocinadoresButton;
    private javax.swing.JButton consultaPorProfesionButton;
    private javax.swing.JButton consultaPorProfesionButton1;
    private javax.swing.JButton consultarGastosButton;
    private javax.swing.JButton consultarMaterialesButton;
    private javax.swing.JButton divisasButton;
    private javax.swing.JButton donacionesButton;
    private javax.swing.JButton donacionesMaterialesButton;
    private javax.swing.JButton donacionesMonetariasButton;
    private javax.swing.JButton epsButton;
    private javax.swing.JButton gastosButton;
    private javax.swing.JButton ingresoDePersonalButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton laboratoriosButton;
    private javax.swing.JButton materialesButton;
    private javax.swing.JButton patrocinadoresButton;
    private javax.swing.JButton personalButton;
    private javax.swing.JButton profesionesButton;
    private javax.swing.JButton subsistemasButton;
    private javax.swing.JButton tipoDePersonaButton;
    private javax.swing.JButton tipoDeSangreButton;
    // End of variables declaration//GEN-END:variables
}
